### ISSUE TITLE
Reusing variables across module methods

### ISSUE THREAD

**Issue by slerman12** [deepmind/sonnet#106]
`@snt.reuse_variables` allows reusing variables in module methods other than `_build()`. However, each method must be the sole owner of its variables. If I want to reuse variables across methods, could I declare them in the module constructor using `with self._enter_variable_scope():` and then simply refer to them in module methods flagged with `@snt.reuse_variables`? Would the flag even be necessary?

**Comment by malcolmreynolds** [comment]
@slerman12 it's correct that you can get the same effects with _enter_variable_scope, however to create actual variables at that point (rather than submodules) it's often not convenient as you won't know the input dimensionality you are dealing with. You can obviously add 'input_size' to the constructor kwargs for a module, but Sonnet generally avoids this in favour of shape inference (as with most of TF).

The original use case for `@reuse_variables` was for VAEs, where it's natural to have multiple externally accessible entry points - ie `encode()` and `decode()` rather than just `_build()`. The idea is that encode and decode have their own disjoint sets of variables (you can obviously come up with exceptions to this, but that's usually the case) and so they are each in charge of building those particular variables. They are built whenever a decorated method is called (which implies that you have some specific input to work with, and can build variables the right size).

The purpose of `_enter_variable_scope` is different - it's for people who prefer declaring their submodules up front, rather than in _build - mostly a stylistic preference.

**Comment by slerman12** [comment]
In the VAE example, it would only be necessary to use the variables of each method in isolation. What if I want to use variables from encode() in decode(), or vice versa? Is there a recommended approach for this besides using the constructor? If I do use the constructor, would I still need to decorate my methods in order to use the constructor variables?

**Comment by malcolmreynolds** [comment]
Sure - let's have an example where encode() requires variables A,B and decode() uses variables B,C. You can't access the B variables with tf.get_variable from both the `snt.reuse_variables` decorated methods - but you can have a third (maybe private) method which access the C variables, and connects them as appropriate.

Let's say you want an autoencoder where some of the weights in encode and decode are tied, specifically the transpose of each other. I'll give examples with hardcoded sizes and no bias for brevity. This won't work because you're accessing c in both methods:

```python
class ModuleA(snt.AbstractModule):
  def __init__(self, name='module_a'):
    super(ModuleA, self).__init__(name=name)

  @snt.reuse_variables
  def encode(self, inputs):
    w_enc_1 = tf.get_variable('w_enc_1', shape=[32, 16])
    c = tf.get_variable('c', shape=[16, 8])

    h = tf.nn.relu(tf.matmul(inputs, w_enc_1))
    return tf.matmul(h, c)

  @snt.reuse_variables
  def decode(self, inputs):
    c = tf.get_variable('c', shape=[16, 8])
    w_dec_1 = tf.get_variable('w_dec_1', shape=[16, 32])

    h = tf.nn.relu(tf.matmul(inputs, tf.transpose(c)))
    return tf.matmul(h, w_dec_1)


  def _build(self, inputs):
    return self.decode(self.encode(inputs))
```

If you factor out the accessing of `c` to a separate method, also decorated, you get this, which will work:

```python
class ModuleB(snt.AbstractModule):
  def __init__(self, name='module_b'):
    super(ModuleB, self).__init__(name=name)

  @snt.reuse_variables
  def _get_common_variable(self):
    return tf.get_variable('c', shape=[16, 8])

  @snt.reuse_variables
  def encode(self, inputs):
    w_enc_1 = tf.get_variable('w_enc_1', shape=[32, 16])
    c = self._get_common_variable()

    h = tf.nn.relu(tf.matmul(inputs, w_enc_1))
    return tf.matmul(h, c)

  @snt.reuse_variables
  def decode(self, inputs):
    c = self._get_common_variable()
    w_dec_1 = tf.get_variable('w_dec_1', shape=[16, 32])

    h = tf.nn.relu(tf.matmul(inputs, tf.transpose(c)))
    return tf.matmul(h, w_dec_1)


  def _build(self, inputs):
    return self.decode(self.encode(inputs))
```

This might seem like a tedious hoop to force users to jump through - but the alternative (allow sharing of c from each method) would mean that the users are responsible for making sure there are no name clashes across all of their reuse_variables decorated methods. If they make a mistake they get unintentional sharing, which could lead to extremely hard to catch bugs.

**Comment by slerman12** [comment]
Great, thank you!
