### ISSUE TITLE
Why is tensorflow-probability required?

### ISSUE THREAD

**Issue by cinjon** [deepmind/sonnet#114]
The tensorflow-probability package seems to be required (see L64 in __init__.py --> `_ensure_dependency_available_at_version('tensorflow_probability', '0.4.0')`), but why is that the case even for gpu installs?

**Comment by malcolmreynolds** [comment]
Tensorflow Probability is required for the Bayes by Backprop custom getter, this is the case regardless of whether or not the GPU versions of TF are used. When you do `pip install tensorflow-probability-gpu`, the library will still be importable in python under the name `tensorflow_probability` (as is the case with TF itself).

Note that if you are wanting to run only GPU versions, then there is currently a bug in the Sonnet install script: https://github.com/deepmind/sonnet/pull/109 - this will be fixed the next time we push a public version. In the meantime, because there is no actual CUDA code in Sonnet any more, you should be able to do the following in a fresh virtualenv to get everything setup:

```shell
pip install tensorflow-gpu tensorflow-probability-gpu
pip install dm-sonnet
```

Please reopen this ticket if you have any problems.
