### ISSUE TITLE
Request for more explanation about VectorQuantizerEMA implementation 

### ISSUE THREAD

**Issue by h-shad** [deepmind/sonnet#120]
Hi,
I am studying the code for VectorQuantizerEMA implementation. In the beginning of it’s _build function there is some comments which says:
>     # Ensure that the weights are read fresh for each timestep, which otherwise
>     # would not be guaranteed in an RNN setup. Note that this relies on inputs
>     # having a data dependency with the output of the previous timestep - if
>     # this is not the case, there is no way to serialize the order of weight
>     # updates within the module, so explicit external dependencies must be used.
I really don’t understand even one sentence of it. What dose this mean? Should we be afraid of it?
And after that there is this piece of code:
```
with tf.control_dependencies([inputs]):
      w = self._w.read_value()
```
I don’t understand why such a control dependency is even needed. And why not simply just use self._w instead of w in the remainder of the code?
Could you please Explain more?
Thanks!

**Comment by malcolmreynolds** [comment]
@h-shad this comment is referring to two fairly subtle issues.

The first is that in this module weights are updated online, rather than during the backwards pass as would be more normal with an RNN setup. Due to the way "legacy" TF 1.0 variables work, if the code was written without this control dependency then the accesses to self._w could be aliased together, so that even for timestep `t` we would use the weights from timestep `0`. In this module, we want for the  the forwards pass for timestep `t+1` to use the weights updated with EMA from timestep `t`, and this control dependency accomplishes that, assuming that the inputs to this module have some ordering dependency.

The latter part of the comment is referring to an additional complication - imagine we have a `VectorQuantizerEMA` used somewhere in the middle of an RL agent. At each timestep, we must execute all the ops, produce an action to give to the environment, which produces the observation as the input for the next timestep. In this case we are fine with the code as written - having a control dependency on `inputs` implies transitively that the whole previous timestep has been executed. Note that switching to resource variables would help here, but we are unable to do this for all of Sonnet due to needing to support legacy codebases.

On the other hand, imagine applying the `VectorQuantizerEMA` to every timestep of some fully known input sequence - eg, in a language model. Then this control dependency on `inputs` does not produce the result we want - TensorFlow could schedule the execution of the ops in any order, for example it could execute the weight updates in the order of `T-1`, `T-2`, ... `0`. This is most likely not what we want, but from inside the code you're pointing to, there's no way to fix it, as we can't see any of the other Tensors we would want to produce a dependency on. If you wanted to do this and have the updates happen in causal order, you would need to use control dependencies at the outer level, as the code says.

If this seems difficult to get your head around - problems like this don't happen in TF 2.0. A version of Sonnet using TF 2.0 / Eager first is under way and will be open sourced when ready.

**Comment by h-shad** [comment]
@malcolmreynolds That was really enlightening for me. I got my answer and also got more (About control dependency usages)! Thank you very much!
