### ISSUE TITLE
Output shape of conv2D transpose with "VALID incorrect

### ISSUE THREAD

**Issue by ferreirafabio** [deepmind/sonnet#127]
```
inputs = tf.placeholder(name='foo', shape=[None, 4, 4, 256],dtype=tf.float32)
snt.Conv2DTranspose(output_channels=256, kernel_shape=4, stride=[1, 2], padding="VALID")(inputs)
```
--> yields shape (?,7,11,256)
```
tf.layers.conv2d_transpose(inputs, filters=256, kernel_size=4, strides=[1, 2], padding='valid')`
```
--> yields shape (?,7,10,256)

Why?

**Comment by tamaranorman** [comment]
It is because the shape of the output can be anywhere within a range instead of being an exact value. Within the tensorflow layers they have chosen to use the minimum default shape wheras in Sonnet we have chosen the maximal.

Within Sonnet you can change the output shape (to any valid shape falling within the range) by using the  `output_shape` kwargs. To get the equivalent in your case use
```snt.Conv2DTranspose(output_channels=256, kernel_shape=4, stride=[1, 2], padding="VALID", output_shape=[7, 10])(inputs)```
