### ISSUE TITLE
Possibly outdated dependency information

### ISSUE THREAD

**Issue by zhengant** [deepmind/sonnet#139]
I'm using a machine where I'm somewhat limited on what versions of packages I can use, but I should ostensibly be able to run sonnet. However, I'm running into a few issues and some of the documentation on the dependency requirements seem inconsistent or incorrect.

System details:
RedHat Enterprise Linux 7.6
CUDA 8.0
CUDNN 7.1

First, the README here states that tensorflow >= 1.5 is supported, but sonnet also requires tensorflow-probability >= 0.4.0. According to https://github.com/tensorflow/probability/releases, tensorflow-probability 0.4.0 is only tested and stable against tensorflow 1.11 and later versions of tensorflow-probability only seem to support more recent versions of tensorflow as well. This seems to imply that tensorflow >= 1.11 is required. I was hoping to be able to run sonnet with tensorflow 1.8.0 but I'm no longer sure if this is possible.

Second, I tried running sonnet with tensorflow 1.12.0 (gpu version) and tensorflow-probability 0.5.0, but I run into this error upon import:
```
>>> import sonnet as snt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sonnet/__init__.py", line 68, in <module>
    from sonnet.python.modules import nets
  File "sonnet/python/modules/nets/__init__.py", line 22, in <module>
    from sonnet.python.modules.nets.alexnet import AlexNet
  File "sonnet/python/modules/nets/alexnet.py", line 37, in <module>
    from sonnet.python.modules import base
  File "sonnet/python/modules/base.py", line 37, in <module>
    from sonnet.python.modules import base_info
  File "sonnet/python/modules/base_info.py", line 24, in <module>
    from sonnet.protos import module_pb2
ImportError: cannot import name module_pb2
```

Finally, when sonnet cannot find a version of tensorflow-probability >= 0.4.0, it says 
```
SystemError: Sonnet requires tensorflow_probability (minimum version 0.4.0) to be installed. If using pip, run `pip install tensorflow-probability` or `pip install tensorflow-probability-gpu`
```
However, tensorflow-probability-gpu doesn't exist anymore starting from tensorflow-probability 0.5.0. I believe the only difference between the cpu and gpu versions was just which version of tensorflow it depended on and they simply removed the dependency in 0.5.0. `pip install tensorflow-probability` should work fine, although if a user wants 0.4.0, then it will also install cpu tensorflow alongside it - this doesn't happen with >= 0.5.0.   

I'd appreciate some clarity on how to work around the first two issues - the third one seems like it should just be an easy change to the error message. Thanks!

**Comment by malcolmreynolds** [comment]
Re 1), we only ensure the library runs with the latest public stable version of TF (and TFP). If you want to use an old version like TF 1.8.0 your best bet is probably going back through sonnet versions to find one that we pushed around that time. All the version dates are in CHANGES.md, and there should be a corresponding git tag, so this shouldn't be a problem. If you _really_ want the latest Sonnet (bear in mind going to our old versions may reintroduce bugs we have now fixed, change interfaces such that code you write then doesn't work on latest version, etc) and you are hard-limited by needing to use an old TF, then you will still probably be able to use some subset of the library, although you might need to comment out various things in Sonnet to get it to import.

I would strongly recommend not doing this if you're doing real work that matters, as there are just too many things at play to predict how well it will work. We have extensive automated testing which exercises current Sonnet and current TF, but you would effectively be using a completely untested configuration, and anything could happen. If you really can't modify your environment to install up to date TF, then an old Sonnet version is better.

You're right that the dependency information is somewhat out of date, and there are different numbers in different places. I believe that we currently require TF >= 1.13 - I'll fix the places that say otherwise.

2) How did you do the install here? `pip install dm-sonnet`, or did you just clone the github repo?

3) Indeed, we should change the error message to not mention `tensorflow-probability-gpu`. Thanks for the report, will be fixed in our next version.

**Comment by zhengant** [comment]
Thanks for your response! I was able to figure out how to get more updated versions of everything and it seems like the library is working fine now.

For 2), I had installed via `pip install dm-sonnet` but I suspect that something went wrong in the course of me uninstalling and reinstalling various versions of tensorflow and tensorflow-probability while debugging earlier - I reinstalled everything on a clean environment and it worked fine.
