### ISSUE TITLE
VQ-VAE inefficient calculation of distances or numerical stability issues?

### ISSUE THREAD

**Issue by fostiropoulos** [deepmind/sonnet#158]
https://github.com/deepmind/sonnet/blob/e097a6678569314f6dd0f0083e91e2cd01aefeff/sonnet/src/nets/vqvae.py#L103
```python
            distances = (
                tf.reduce_sum(flat_inputs**2, 1, keepdims=True) -
                2 * tf.matmul(flat_inputs, self.embeddings) +
                tf.reduce_sum(self.embeddings**2, 0, keepdims=True))
```

Is it due to some numerical stability issue? It seems to be the expanded form of what I wrote below. It would make much more sense to calculate the distances as such:

```python
distances = tf.reduce_sum((flat_inputs - self.embeddings) ** 2, axis=-1)
```

I can create a pull request if necessary :)

**Comment by malcolmreynolds** [comment]
The two code segments are not equivalent - the code as it exists in the module is computing the distance between every corresponding pair of entries flat_input and embedding, and note that it will work for different size inputs as long as flat_inputs.shape[1] == self.embeddings.shape[0]. Your version only computes the distance for when you have an equal number of flat inputs and embeddings, which is not necessarily going to be true, and more importantly it computes the distance from minibatch element i to embedding i only, instead of the all pairs version.

Hope this helps, please reopen if this is not clear.

**Comment by fostiropoulos** [comment]
@malcolmreynolds I don't quite see the difference yet so I will give it some more thought.

Also why do 
https://github.com/deepmind/sonnet/blob/e097a6678569314f6dd0f0083e91e2cd01aefeff/sonnet/src/nets/vqvae.py#L108
```python
encoding_indices = tf.argmax(-distances, 1)
```

instead of 

```python
encoding_indices = tf.argmin(distances, 1)
```

**Comment by malcolmreynolds** [comment]
Maybe I can explain better.. Let's say you have an embedding dimension of 4, dictionary size / num_embeddings of 5, so self.embeddings will have shape [4, 5].

The code as written allows users to pass in any tensor with a final dimension of 4 - all the preceding dimensions are flattened to a single one, which we could think of as batch size. So inputs with shape [7, 4] produces a flat_input of shape [7, 4] again. Inputs of shape [3, 11, 4] produ ces flat_inputs of shape [33, 4].

Now let's say we have some flat_inputs of shape [3, 4], and for each of them we want to compute the distance to each embedding, which we then find the minimum distance of. The code as written for distances produces an output of size [33, 5], where element i,j is the distance between input element i and dictionary element j. This is all the possible pairwise distances that can be calculated, which your code does not do.

Your suggestion will only "work", as in run without an error, for flat_inputs having the same shape as (or a shape broadcastable to the shape of) the embeddings - but the distances generated by your code will only contain the distances between input element i and dictionary element i. You can't do the following argmax (or argmin!) because you don't have all the relevant distances calculated.

Possibly your confusion is that you're thinking about an input of batch size 1 only - through broadcasting, your approach does compute all the distances required - but essentially through luck, and if you go to batch size >=2 the calculation will fail. Arbitrary batch sizes should be supported basically everywhere in Sonnet because that's how this code is run in practice,


As for argmin versus argmax, this is a good question. I'm actually not sure if there is a microoptimisation at play here or whether it's a stylistic preference - I did a little cleanup and added docs for the release but all the logic is unchanged from the original implementation by Aäron van den Oord, including that detail.

**Comment by fostiropoulos** [comment]
@malcolmreynolds After some thought, maybe it wasn't clear what I was trying to describe.
What if instead of flat_inputs it was shaped as [B,1,D] and embeddings as [1,K,D] wouldn't that produce equivalent results with far fewer computations?
