### ISSUE TITLE
TpuReplicator usage is not clear

### ISSUE THREAD

**Issue by dangerzone** [deepmind/sonnet#183]
Hello,

I'm interested in using `TpuReplicator` to train on multiple TPU devices that are not part of a pod. The class documentation isn't clear on how to specify device name/location to this strategy.  For example `tf.TPUStrategy` (which `TpuReplicator` class inherits)  requires a `tf.TPUClusterResolver` to tell it about the TPU cluster, but no such information is given for `snt.TpuReplicator` in the documentation.

If `tf.TPUClusterResolver` is also used here, that would cause a problem because `tf.TPUClusterResolver` doesn't support multiple TPU devices.

I would really appreciate an example or explanation of how to use this strategy.

**Comment by tomhennigan** [comment]
Hey @dangerzone, `TpuReplicator` is now equivalent to `TPUStrategy`, there used to be one key difference (`TpuReplicator` used to create **replicated** variables [e.g. same initial value but not required to be in sync otherwise] while `TPUStrategy` used to require **mirrored** variables [meaning you need to use a special API for assignment to ensure values remained mirrored]) but TF team recently (I think you may need to use [TF 2.3.0rc2](https://pypi.org/project/tensorflow/2.3.0rc2/)) relaxed `TPUStrategy` (and `MirroredStrategy`) to not require using this mirrored assignment API.

As such I would suggest looking for any docs for `TPUStrategy` that explain how to do what you want. Usage (constructor etc) with `TpuReplicator` would be equivalent.

In the next release of Sonnet we will likely make `TpuReplicator` an alias for `TPUStrategy` and remove the symbol entirely in a future release. Before doing this we want to find some time to run a few experiments to make sure there are no surprises.
