### ISSUE TITLE
Building encoder decoder?

### ISSUE THREAD

**Issue by leesunfreshing** [deepmind/sonnet#35]
I am now trying to build a Lstm encoder decoder framework using sonnet and tensorflow. I understand sonnet have the lstm module involved. I was trying to build encoder decoder with tf.contrib.seq2seq.decoder. However, I am not sure if this one builds encoder implicitly, and the decoder_inputs are encoder_input? Since in my case, I do not have any input for decoder but the output from previous step... 
Is there any warpper in Sonnet for this kind of issue? Can you suggest some proper way to do this?

**Comment by malcolmreynolds** [comment]
@leesunfreshing Hi, we don't have anything seq2seq specific in Sonnet. The RNN cores we have should be compatible with the TF RNN containers (eg tf.nn.dynamic_rnn) so I imagine using a sonnet module will work... As far as I can see only the decoder is provided because you need to be feeding the decoder always with the output of the previous timestep, and there is also the opportunity to do beam search which requires extra code. For the encoder, you simply feed your sequence into a (different) RNN in the standard way (tf.nn.dynamic_rnn), ignore the output sequence and then use the final hidden state as the input to the decoder. I'm not an expert on seq2seq, but I believe this is why they didn't provide any special code for the encoder.

If you have further questions on this I suggest filing an issue on the main TF GitHub.
