### ISSUE TITLE
I herd results build from source but that could be more problems

### ISSUE THREAD

**Issue by josheeg** [deepmind/sonnet#42]
Hi the install on this is very hard I do not know if resample is a module... I tried finding one and installing it.
I tried anaconda
I tried the gpu version first and figured uninstall and use python 2 and try with cpu only and minimal configuration no gpu no opencl...
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sonnet as snt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sonnet/__init__.py", line 103, in <module>
    from sonnet.python.ops.resampler import resampler
  File "/usr/local/lib/python2.7/dist-packages/sonnet/python/ops/resampler.py", line 33, in <module>
    tf.resource_loader.get_path_to_datafile("_resampler.so"))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python2.7/dist-packages/sonnet/python/ops/_resampler.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

**Comment by Shuolongbj** [comment]
Configure TensorFlow Headers,This step is necessary so that Sonnet can build against the TensorFlow headers.

FYI.
cd sonnet/tensorflow
git checkout r1.2
./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
pip uninstall tensorflow
pip install /tmp/tensorflow_pkg/tensorflow-1.2.0-cp36-cp36m-macosx_10_7_x86_64.whl
cd ../
bazel build --config=opt //:install
bazel-bin/install /tmp/sonnet_pkg
pip uninstall sonnet
pip install /tmp/sonnet_pkg/sonnet-1.2-py3-none-any.whl

**Comment by malcolmreynolds** [comment]
Hi @josheeg  - please see https://github.com/deepmind/sonnet/issues/56 - there are preliminary Wheel files available on PyPI. Please try to install using that and let us know how you get on.
