### ISSUE TITLE
Avoid duplicated scope names when using `_enter_variable_scope`.

### ISSUE THREAD

**Issue by vierja** [deepmind/sonnet#50]
It seems like when you are using `self._enter_variable_scope` in the `__init__` you end up with a `"module"_1` scope for you main ops.

It's very annoying and confusing to look at the Tensorboard when that happens (example below).

I've written a [simple two-submodule module in Sonnet](https://gist.github.com/vierja/668d8985746b0d5ba15fc038e130d150). The prints I get are:
```
['main_module_1/submodule_a/Variable:0', 'main_module_1/submodule_b/Variable:0']
['main_module/submodule_a/Variable:0', 'main_module/submodule_b/Variable:0']
```

I tried looking into how to "fix" it but I need some guidance of the possible ways to do it (without tearing the whole thing apart).

![image](https://user-images.githubusercontent.com/653497/28148928-377e1c96-6760-11e7-93f7-b575c3201886.png)

**Comment by tfgg** [comment]
Thanks for the report and clear example. It looks like it's because you created the variables with tf.Variable rather than tf.get_variable, this is known to interact poorly with variable scopes. It's [mentioned in the docs](https://deepmind.github.io/sonnet/#implement-build-method) but might be a bit buried.

Here's my code:
https://gist.github.com/tfgg/d815ec514697a16bc1067acdbb6f0e1f
which outputs
```
[u'main_module/submodule_a/a:0', u'main_module/submodule_b/b:0']
[u'main_module/submodule_a/a:0', u'main_module/submodule_b/b:0']
```

**Comment by vierja** [comment]
@tfgg Thanks for the clarification and the example! I must have missed that bit in the docs. I'm not creating any variables directly so it's probably down to some TF slim utils.

Besides being kind of annoying, does this behaviour cause any unwanted effects on the computation?

Closing the issue, thanks!.

**Comment by tfgg** [comment]
I'm not 100% sure, but I think variable sharing would fail (since it's creating a new variable each time), but I'd want to check that first :)

It's certainly possible that something in TF-slim caused this, it might not always interact well with Sonnet, though I think that also uses tf.get_variable.
