### ISSUE TITLE
Avoid duplicated scope names (for operations?) when using `_enter_variable_scope`

### ISSUE THREAD

**Issue by vierja** [deepmind/sonnet#53]
Continuing on #50 I am still not sure the `self._enter_variable_scope` is having the correct effect on operation naming in Tensorboard.

I've written a [simple module -> submodule example](https://gist.github.com/vierja/d0879ff294a784758730fa92a4973005) with and without `_enter_variable_scope` and I've got different graphs in Tensorboard.

Even though the variables end up being the same:
```
['main_module/linear/w:0', 'main_module/linear/b:0']
['main_module/linear/w:0', 'main_module/linear/b:0']
```

I get these two different graphs in Tensorboard:

with `snt.Linear`defined on the `_build` method:
![image](https://user-images.githubusercontent.com/653497/28243316-58c4b594-699b-11e7-8d95-b2ae904b7c14.png)

with `snt.Linear` defined on the init with `_enter_variable_scope`:
![image](https://user-images.githubusercontent.com/653497/28243312-48cd07d6-699b-11e7-87f8-56b33e7d452a.png)

**Comment by Shuolongbj** [comment]
well done.I think your method is better than official.Please try to send PR, of course, may not be able to merge

**Comment by vierja** [comment]
@Shuolongbj you mean changing the docs or change sonnet in order to behave the same way for both examples? The latter I'm not sure how to do, any insight is much appreciated.

**Comment by vierja** [comment]
@tfgg any feedback on this?

**Comment by malcolmreynolds** [comment]
@vierja The reason for the discrepancy is that _enter_variable_scope vs defining submodules in _build only unifies the variable_scopes entered, meaning that the variables have the same name whichever way round you do it. However, every time you enter the variable_scope you get a new name scope which will be uniquified if necessary by adding _N. The Tensorboard graph visualises namescopes, rather than variable scopes per se, although there is obviously overlap.

In your second example, the variables (and the ops associated with them - read, assign, init etc) are inside the first time you enter name_scope, which is `main_module` at the bottom. When you call _build, you reenter a name_scope with the same name and TF uniquifies it to `main_module_1`, and you see the add and matmul inside the smaller block up top. If you connect the module a second time you would get another small block, `main_module_2`, with again just a Matmul and Add inside. Similarly, if you connect the module a second as you have it written in the first module, you also get a second block as the name_scope is entered a second time.

I don't think it's possible to change this name_scope behaviour without some hacking of TF, and I don't think that would necessarily be desirable - when connecting modules multiple times you probably want that to show as separate name_scopes in Tensorboard. Otherwise, a module shared lots of times would end up looking extremely confusing as all the input / output connections go through one block.

I hope this explanation helps - please let me know if you have other comments or questions.

**Comment by fastturtle** [comment]
Thanks for bringing this to our attention. The issue here is that `_enter_variable_scope()` enters a `tf.variable_scope()`, which creates a name scope. This ultimately [increments the counter](url) the `tf.Graph` object uses to uniquify name scopes. The result is that if you use `_enter_variable_scope()` to define variables inside `__init__`, then when  `_build()` is called for the first time the name scope has "_1" appended to it.

This is common behavior in TensorFlow and occurs when variables are created before they are used, for example:
```python
with tf.variable_scope("scope"):
  v = tf.get_variable("v", shape=[])
  
with tf.variable_scope("scope", reuse=True):
  # We have now entered the name_scope "scope_1"
  x = v * 2
```

![image](https://user-images.githubusercontent.com/1386091/28566343-c74ae8fc-7126-11e7-8582-3e9996099640.png)

It sounds like you want  to enter a variable scope _without_ entering a name scope. I would advise against this, because it can lead to even weirder graphs (what happens if you accidentally create an Op?) and isn't possible with public TensorFlow functions. Did you have a different solution in mind?

**Comment by vierja** [comment]
@malcolmreynolds and @fastturtle, thank you guys for your explanations and for making me understand why it wouldn't be necessarily an undesirable behavior. I can't think of a different solution and mostly it seems that this is the desired visualization. I appreciate your time.
