### ISSUE TITLE
Too strict sanity check on initializer dict

### ISSUE THREAD

**Issue by mingyr** [deepmind/sonnet#93]
Dear deepminder:

I constructed a model using snt.Conv2D and snt.SeparableConv2D. When I create an initializer dict and pass it to the constructor, it complains.

The initializer dict I constructed is as follows:
```
        initializers = {"w": tf.contrib.layers.xavier_initializer(),
                        "w_dw": tf.contrib.layers.xavier_initializer(),
                        "w_pw": tf.contrib.layers.xavier_initializer(),
                        "b": tf.zeros_initializer()
        }

```

And the complain message is as follows:
```
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/sonnet/python/modules/util.py", line 170, in check_initializers
    ", ".join("'{}'".format(key) for key in keys)))
KeyError: "Invalid initializer keys 'w_pw', 'w_dw', initializers can only be provided for 'b', 'w'"
SIGCHLD received

```

I personally thinking it is not necessary for constructing initializers for snt.Conv2D and snt.SeparableConv2D separately since it is a little redundant, how about relieve sanity check on the keys?

**Comment by kosklain** [comment]
Hi,

Thanks for the question. In our experience, since the name of the variables are quite short (sometimes following paper notation), it has been easy to make typos and has bitten us in the past :) So we prefer erring on the strict side on this one. I apologize, as I understand this might not be the most convenient specification sometimes.

**Comment by mingyr** [comment]
Fully understanding, so I will close the thread.
